### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by rahman9909** [shaansubbaiah/Flashcards#1]
Tried upgrading 
animated_splash_screen: ^1.1.0

Still showing error right after the logo splash. 

════════ Exception caught by widgets library ═══════════════════════════════════
The following _CastError was thrown building AnimatedBuilder(animation: Listenable.merge([kAlwaysCompleteAnimation➩ProxyAnimation, kAlwaysDismissedAnimation➩ProxyAnimation]), dirty, state: _AnimatedState#91fe2):
Null check operator used on a null value

The relevant error-causing widget was
MaterialApp
lib/main.dart:48
When the exception was thrown, this was the stack
#0      new PageTransition.<anonymous closure> (package:page_transition/src/page_transition.dart:199:39)
#1      PageRouteBuilder.buildTransitions (package:flutter/src/widgets/pages.dart:116:30)
#2      _ModalScopeState.build.<anonymous closure>.<anonymous closure> (package:flutter/src/widgets/routes.dart:817:49)
#3      AnimatedBuilder.build (package:flutter/src/widgets/transitions.dart:1468:19)
#4      _AnimatedState.build (package:flutter/src/widgets/transitions.dart:174:48)

**Comment by rahman9909** [comment]
It is an issue with the animated_splash_screen package. 

Changing the transition type resolves the issue for now : PageTransitionType.fade
